[package]
name = "pendulum"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
num-complex = "0.4.0"
ndarray-linalg = "0.16.0"
ndarray = "0.16.1"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]
